# show just commands
default:
    just --list

# build backend executable
build:
    mkdir -p build && go build -o build/main

# generate build code
generate:
    go generate ./...

# run test suite
test:
    go test -cover ./...

# run test suite and produce coverage report
test-cover:
    go install github.com/axw/gocov/gocov@latest
    go test -coverprofile=coverage.out ./...

# format code
fmt:
    go fmt

# tidy go modules
tidy:
    go mod tidy

# run test suite inside docker for CI
test-ci:
    docker run --rm -v $(pwd):/work -w /work golang:1.21-alpine sh -c "apk add --no-cache just && just test-cover"