version: '3'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: meilisearch
    env_file:
      - .env
    environment:
      - MEILI_NO_ANALYTICS=true
    ports:
      - 0.0.0.0:7700:7700
    volumes:
      - ./tmp/meili:/meili_data
    user: "1000:1000"
  meilisearch-init:
    image: alpine:latest
    container_name: meilisearch-init
    command: sh -c "apk add --no-cache curl && sh /data/index_settings.sh"
    env_file:
      - .env
    volumes:
      - ./data/index_settings.sh:/data/index_settings.sh
    depends_on:
      - meilisearch
 
  neo4j:
    image: neo4j:5-bullseye
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    volumes:
      - ./tmp/neo:/data
    env_file:
      - .env
    user: "1000:1000"

  backend:
    image: chain-react-server
    container_name: backend
    build:
      context: ../backend
    ports:
      - 8080:8080
    volumes:
      - ./data/backend/.chain-react.yaml:/app/.chain-react.yaml:ro

  frontend:
    image: chain-react-frontend
    container_name: frontend
    build:
      context: ../frontend
    ports:
      - 3000:80

  proxy:
    image: caddy:2.6.4-alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data
      - ./../frontend/build:/var/www/chainreact:ro
