version: '3'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: meilisearch
    env_file:
      - .env
    environment:
      - MEILI_NO_ANALYTICS=true
    ports:
      - 0.0.0.0:7700:7700
    volumes:
      - .${CR_DOCKER_DATA}/meili:/meili_data
    user: "1000:1000"
    restart: unless-stopped

  meilisearch-init:
    image: alpine:latest
    container_name: meilisearch-init
    command: sh -c "apk add --no-cache curl && sh /data/index_settings.sh"
    env_file:
      - .env
    volumes:
      - ./index_settings.sh:/data/index_settings.sh
    depends_on:
      - meilisearch
 
  neo4j:
    image: neo4j:5-bullseye
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    volumes:
      - ${CR_DOCKER_DATA}/neo:/data
    env_file:
      - .env
    user: "1000:1000"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: >
      redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${CR_DOCKER_DATA}/redis:/data

  backend:
    image: ghcr.io/jj-style/chain-react:master
    container_name: backend
    build:
      context: ../backend
    ports:
      - 8080:8080
    volumes:
      - ./.chain-react.yaml:/app/.chain-react.yaml:ro
    restart: unless-stopped
    depends_on:
      - redis
      - neo4j
      - meilisearch

  proxy:
    image: caddy:2.6.4-alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CR_DOCKER_DATA}/caddy:/data
      - ./../frontend/build:/var/www/chainreact:ro
    restart: unless-stopped
