name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: taiki-e/install-action@just
      
      - name: Run tests and publish coverage
        run: just test-ci
        working-directory: backend
      
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
        working-directory: backend